# pull official base image
FROM lesa_base:latest

# This flag is important to output python logs correctly in docker!
ENV PYTHONUNBUFFERED 1
# Flag to optimize container size a bit by removing runtime python cache
ENV PYTHONDONTWRITEBYTECODE 1

# create the appropriate directories
ENV BOT_HOME=/lesa

WORKDIR $BOT_HOME

# copy project
COPY . $BOT_HOME

RUN ["python3", "init.py"]

CMD ["python3", "__main__.py"]

