version: '3.8'
services:
  lesa:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./data:/home/lesa/data
      - ./log:/home/lesa/logs
    ports:
      - "8443:8443/tcp"
      - "443:443/tcp"
    restart: always

