version: '3.8'
services:
  lesa:
    build:
      context: .
      dockerfile: Dockerfile_from_base
    volumes:
      - ./data:/data
      - ./log:/logs
    ports:
      - "8443:8443/tcp"
      - "443:443/tcp"
    restart: always